name: STEMCraft
main: com.stemcraft.STEMCraft
version: ${project.version}
api-version: 1.19
author: nomadjimbob
website: https://stemcraft.com.au
description: Provides utilities for the STEMCraft server
softdepend: [NBTAPI, PlaceholderAPI, Citizens, ItemsAdder, WorldEdit, WorldGuard, Vault, LuckPerms]
